export const LANGUAGES = {
	en: 'English',
	ja: 'Japanese',
	zh: 'Chinese',
	es: 'Spanish',
	fr: 'French',
	de: 'German',
	ko: 'Korean',
	ru: 'Russian',
	pt: 'Portuguese',
	it: 'Italian',
	ar: 'Arabic',
	hi: 'Hindi',
	bn: 'Bengali',
	pa: 'Punjabi',
	ur: 'Urdu',
	fa: 'Persian',
	tr: 'Turkish',
	nl: 'Dutch',
	id: 'Indonesian',
	th: 'Thai',
	vi: 'Vietnamese',
	el: 'Greek',
	he: 'Hebrew',
	pl: 'Polish',
	cs: 'Czech',
	sk: 'Slovak',
	sl: 'Slovenian',
	hu: 'Hungarian',
	ro: 'Romanian',
	bg: 'Bulgarian',
	uk: 'Ukrainian',
	be: 'Belarusian',
	kz: 'Kazakh',
	uz: 'Uzbek',
	am: 'Amharic',
	et: 'Estonian',
	lv: 'Latvian',
	lt: 'Lithuanian',
}

export default {}
